# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-21 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xcourses', '0002_auto_20170821_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='course_download/%Y/%m', verbose_name='封面'),
        ),
    ]
