# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-23 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xcourses', '0003_auto_20170821_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='后端开发', max_length=20, verbose_name='学习方向'),
        ),
    ]
