# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-24 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xcourses', '0005_course_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url_address',
            field=models.CharField(default='', max_length=200, verbose_name='视频地址'),
        ),
    ]
