# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-24 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xcourses', '0006_video_url_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='learn_times',
            field=models.CharField(default=0, max_length=8, verbose_name='小节视频长度'),
        ),
    ]
