# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-24 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_teacher_image'),
        ('xcourses', '0007_video_learn_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='procla',
            field=models.CharField(default='', max_length=100, verbose_name='课程公告'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Teacher', verbose_name='授课讲师'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_talks',
            field=models.CharField(default='', max_length=300, verbose_name='老师心得'),
        ),
    ]
