# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-30 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailveritfyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '找回密码'), ('upload', '更改邮箱')], max_length=10, verbose_name='验证码类型'),
        ),
    ]
