# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-28 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='years',
            field=models.IntegerField(default=0, verbose_name='年龄'),
        ),
    ]
